//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalDemin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public Nullable<int> IdMark { get; set; }
        public Nullable<int> IdActivity { get; set; }
        public Nullable<System.DateTime> DateGr { get; set; }
        public Nullable<int> IdGroups { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Mark Mark { get; set; }
    }
}
